language: android
android:
  components:
  - android-29
  - build-tools-29.0.2
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
script:
- "./gradlew clean assembleDebug assembleRelease testDebug"

before_install:
- openssl aes-256-cbc -K $encrypted_6fa16f9363b5_key -iv $encrypted_6fa16f9363b5_iv
  -in OurStore.keystore.enc -out OurStore.keystore -d

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  user: "heba@shourasoft.com"
  password: "305MAAMOONmaamoon"
  file_glob: true
  file: /Users/shourasoftmac/Downloads/TraviseCiCdTest/app/build/outputs/apk/release/*
  on:
    repo: hebaNada/TraviseCiCdTest
    tags: false