language: android
android:
  components:
  - android-29
  - build-tools-29.0.2
env:
  global:
  - ADB_INSTALL_TIMEOUT=8

script:
- "./gradlew assembleRelease"
before_install:
- openssl aes-256-cbc -K $encrypted_6fa16f9363b5_key -iv $encrypted_6fa16f9363b5_iv
  -in OurStore.keystore.enc -out OurStore.keystore -d

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: b1xAzPBNwt2mxTnAykXD/9enikrPKgYG8Tjn2Mwz0T66Vkwp3OYQD9cMbMuABzAo1K1gzAqKc9GBn+YZo0n/4iOqdOYe+uu9swD7WMfQ/3K5Le0zSBMtUqA7c1st4PcK8v0Rz8eJdsXZPOT78Rd9nPbrqhHYz6wMRoXAE3gFz4THk3AAMotXDz66gDomBdguMFYDVYFWcbM2AKDvBY5TYonNiwqCEWYuj7FzfA7ua4MteaGqwYhiOSxpRCCQRiEteDut+lIrnaJzREaxD2o1JStp7NUjJtL6acJKNHf0J5w9gUXeEaqVqDcuKflrYsjgOOI187McoJJACN988eK+l3WFVdLZWqe2cThc0sAOqCpArJQtUqfPD2cgOsDQaCeBRbDK8GfpcD0t8z3EU2Z0gwas41IFrO99/Z+BG2Q9uB7XcSEgqS2wHHLkcRRv3OTSwKg9b9vEXmuCs+OFK33wHbs542lfuHhtGMx+Cxti0soQ6LTSD/tRphpRwHZpkOgzjzaK0l3zb4ylkHqdX76wPJ/Y/rEfjR5ZueWQjt/S+lHq6cN1M+OmD1AiimkpNo6NkQXgQcHQ5YjbPSDa7UYHCuXda45tO1GT7fA43F52pFgOgbQoARFTwUraN9mxpYdCBldj2XCpDFKLGN0t4ULOnGL8zHLDrVau1KX1Io6CC+M=
  file_glob: true

  file: /home/travis/build/hebaNada/TraviseCiCdTest/app/build/outputs/apk/release/*

  on:
    repo: hebaNada/TraviseCiCdTest
    tags: false
