language: android
android:
  components:
    - android-29
    - build-tools-29.0.2

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug assembleRelease testDebug

deploy:
  provider: releases
  api_key:
    secure: "w6icrhYz89kR7WW1FlXCZA"
  file: "/Users/shourasoftmac/Downloads/TraviseCiCdTest/build/outputs/apk/TraviseCiCdTest.apk"
  file_glob: "true"
  skip_cleanup: true
  on:
    branch: master
    repo: hebaNada/TraviseCiCdTest